/**
 * generate_test_template - Generate E2E test template for a feature
 *
 * This tool generates a Playwright E2E test template based on the feature type.
 * Helps ensure every feature has at least one test before merge.
 */

import { existsSync, writeFileSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';

export interface GenerateTestTemplateParams {
  worktree_path?: string;
  feature_name: string;
  type: 'frontend' | 'api' | 'both';
  base_url?: string;
}

export interface GenerateTemplateResult {
  success: boolean;
  file_path: string;
  content: string;
  type: string;
  message: string;
}

const FRONTEND_TEMPLATE = `import { test, expect } from '@playwright/test';

/**
 * E2E tests for {{FEATURE_NAME}}
 *
 * Generated by Smart Agent Workflow MCP
 *
 * Requirements:
 * - At least one test MUST pass before merge
 * - Use descriptive test names
 * - Test user-facing behavior, not implementation
 */

test.describe('{{FEATURE_NAME_TITLE}}', () => {
  test.beforeEach(async ({ page }) => {
    // Navigate to the feature page
    await page.goto('{{BASE_URL}}');
  });

  test('should render the main component', async ({ page }) => {
    // TODO: Replace with actual selectors
    await expect(page.locator('[data-testid="{{FEATURE_NAME}}-container"]')).toBeVisible();
  });

  test('should handle user interaction', async ({ page }) => {
    // TODO: Add user interaction test
    // Example:
    // await page.click('[data-testid="{{FEATURE_NAME}}-button"]');
    // await expect(page.locator('[data-testid="{{FEATURE_NAME}}-result"]')).toBeVisible();
  });

  test('should be accessible', async ({ page }) => {
    // Basic accessibility checks
    const mainContent = page.locator('main, [role="main"], #main-content');
    await expect(mainContent).toBeVisible();
  });
});
`;

const API_TEMPLATE = `import { test, expect } from '@playwright/test';

/**
 * API tests for {{FEATURE_NAME}}
 *
 * Generated by Smart Agent Workflow MCP
 *
 * Requirements:
 * - At least one test MUST pass before merge
 * - Test both success and error cases
 * - Validate response schemas
 */

test.describe('{{FEATURE_NAME_TITLE}} API', () => {
  const baseURL = '{{BASE_URL}}';

  test('should return 200 for GET request', async ({ request }) => {
    const response = await request.get(\`\${baseURL}/api/{{FEATURE_NAME}}\`);

    expect(response.status()).toBe(200);

    const data = await response.json();
    expect(data).toBeDefined();
  });

  test('should handle POST request', async ({ request }) => {
    const response = await request.post(\`\${baseURL}/api/{{FEATURE_NAME}}\`, {
      data: {
        // TODO: Add request body
      },
    });

    expect(response.status()).toBe(201);
  });

  test('should return 400 for invalid input', async ({ request }) => {
    const response = await request.post(\`\${baseURL}/api/{{FEATURE_NAME}}\`, {
      data: {
        invalid: 'data',
      },
    });

    expect(response.status()).toBe(400);
  });

  test('should return 404 for non-existent resource', async ({ request }) => {
    const response = await request.get(\`\${baseURL}/api/{{FEATURE_NAME}}/non-existent-id\`);

    expect(response.status()).toBe(404);
  });
});
`;

const COMBINED_TEMPLATE = `import { test, expect } from '@playwright/test';

/**
 * E2E tests for {{FEATURE_NAME}}
 *
 * Generated by Smart Agent Workflow MCP
 *
 * This test file covers both frontend UI and backend API tests.
 * Requirements:
 * - At least one test MUST pass before merge
 * - Test the complete user flow
 */

test.describe('{{FEATURE_NAME_TITLE}} - Full Stack', () => {
  const baseURL = '{{BASE_URL}}';

  test.describe('Frontend', () => {
    test.beforeEach(async ({ page }) => {
      await page.goto(baseURL);
    });

    test('should render correctly', async ({ page }) => {
      await expect(page.locator('[data-testid="{{FEATURE_NAME}}-container"]')).toBeVisible();
    });

    test('should interact with backend', async ({ page }) => {
      // TODO: Test frontend-backend integration
      // Example:
      // await page.fill('[data-testid="{{FEATURE_NAME}}-input"]', 'test data');
      // await page.click('[data-testid="{{FEATURE_NAME}}-submit"]');
      // await expect(page.locator('[data-testid="{{FEATURE_NAME}}-result"]')).toHaveText(/success/i);
    });
  });

  test.describe('API', () => {
    test('should return valid data', async ({ request }) => {
      const response = await request.get(\`\${baseURL}/api/{{FEATURE_NAME}}\`);

      expect(response.status()).toBe(200);

      const data = await response.json();
      expect(data).toBeDefined();
    });

    test('should handle errors gracefully', async ({ request }) => {
      const response = await request.post(\`\${baseURL}/api/{{FEATURE_NAME}}\`, {
        data: {},
      });

      // Should return 4xx for invalid request
      expect(response.status()).toBeGreaterThanOrEqual(400);
      expect(response.status()).toBeLessThan(500);
    });
  });

  test('complete user flow', async ({ page, request }) => {
    // 1. Load the page
    await page.goto(baseURL);

    // 2. TODO: Complete user flow test
    // - Fill form
    // - Submit
    // - Verify API was called
    // - Verify UI updated
  });
});
`;

/**
 * Generate E2E test template
 */
export async function generateTestTemplate(params: GenerateTestTemplateParams): Promise<GenerateTemplateResult> {
  const {
    worktree_path = process.cwd(),
    feature_name,
    type,
    base_url = 'http://localhost:3000',
  } = params;

  // Validate worktree path exists
  if (!existsSync(worktree_path)) {
    throw new Error(`Worktree path does not exist: ${worktree_path}`);
  }

  // Sanitize feature name for file system
  const safeFeatureName = feature_name
    .toLowerCase()
    .replace(/[^a-z0-9]/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '');

  // Create title case version
  const featureNameTitle = feature_name
    .split(/[-_\s]+/)
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');

  // Select template based on type
  let template: string;
  switch (type) {
    case 'frontend':
      template = FRONTEND_TEMPLATE;
      break;
    case 'api':
      template = API_TEMPLATE;
      break;
    case 'both':
      template = COMBINED_TEMPLATE;
      break;
    default:
      throw new Error(`Invalid test type: ${type}. Must be 'frontend', 'api', or 'both'.`);
  }

  // Replace placeholders
  const content = template
    .replace(/\{\{FEATURE_NAME\}\}/g, safeFeatureName)
    .replace(/\{\{FEATURE_NAME_TITLE\}\}/g, featureNameTitle)
    .replace(/\{\{BASE_URL\}\}/g, base_url);

  // Determine file path
  const testsDir = join(worktree_path, 'tests', 'e2e');
  const filePath = join(testsDir, `${safeFeatureName}.spec.ts`);

  // Check if file already exists
  if (existsSync(filePath)) {
    return {
      success: false,
      file_path: filePath,
      content: '',
      type,
      message: `Test file already exists: ${filePath}. Delete it first if you want to regenerate.`,
    };
  }

  // Create directory if it doesn't exist
  if (!existsSync(testsDir)) {
    mkdirSync(testsDir, { recursive: true });
  }

  // Write the file
  writeFileSync(filePath, content);

  return {
    success: true,
    file_path: filePath,
    content,
    type,
    message: `Test template created at ${filePath}. Edit the TODOs and run tests with 'npx playwright test ${filePath}'`,
  };
}

/**
 * Tool definition for MCP
 */
export const generateTestTemplateDefinition = {
  name: 'generate_test_template',
  description: 'Generates a Playwright E2E test template for a feature. Every feature MUST have tests before merge.',
  inputSchema: {
    type: 'object' as const,
    properties: {
      worktree_path: {
        type: 'string',
        description: 'Path to the worktree or project directory. Defaults to current directory.',
      },
      feature_name: {
        type: 'string',
        description: 'Name of the feature (e.g., "user-authentication", "dark-mode-toggle")',
      },
      type: {
        type: 'string',
        enum: ['frontend', 'api', 'both'],
        description: 'Type of test to generate: frontend (UI), api (backend), or both',
      },
      base_url: {
        type: 'string',
        description: 'Base URL for tests. Default is http://localhost:3000',
        default: 'http://localhost:3000',
      },
    },
    required: ['feature_name', 'type'],
  },
};
